/*
 * Houston Emerging Sector Radar
 * © 2026 SheIgnite Society LLC. All rights reserved.
 * Proprietary and confidential. No license is granted to copy, modify,
 * or distribute this code without written permission.
 */
export const SKILLS = [
  { id: "pm", label: "Project management" },
  { id: "ops", label: "Operations" },
  { id: "safety", label: "Safety & compliance" },
  { id: "tech", label: "Engineering & technical" },
  { id: "data", label: "Data & analysis" },
  { id: "finance", label: "Finance" },
  { id: "sales", label: "Sales & business development" },
  { id: "logistics", label: "Logistics & supply chain" },
  { id: "client", label: "Customer & client relations" },
  { id: "training", label: "Training & education" },
] as const;

export const RADAR_FOLLOW_SECTORS = [
  { id: "energy-transition", name: "Energy & Climate" },
  { id: "digital-infrastructure", name: "Technology & Digital Infrastructure" },
  { id: "health-life-sciences", name: "Health & life sciences" },
  { id: "construction", name: "Construction" },
  { id: "advanced-logistics", name: "Advanced logistics" },
  { id: "commercial-space", name: "Aerospace" },
] as const;

export const SECTORS = [
  {
    id: "hydrogen",
    name: "Hydrogen",
    industry: "Energy & Climate",
    momentum: "rising",
    why: "The Houston area already produces and uses hydrogen at large scale for refining and chemicals, so the region has the plants, pipelines, and experienced people to build on.",
    work: "Running and maintaining production facilities, managing safety, developing new projects, and negotiating supply deals with industrial customers.",
    skills: ["ops", "safety", "pm", "tech", "sales"],
    verified: false,
    verifiedBy: "",
  },
  {
    id: "ccs",
    name: "Carbon capture & storage",
    industry: "Energy & Climate",
    momentum: "rising",
    why: "The Gulf Coast combines large industrial sites, suitable underground geology, and deep oil and gas expertise, making it one of the most active regions for carbon capture projects.",
    work: "Planning and permitting projects, monitoring storage sites, operating capture equipment, and reporting on compliance.",
    skills: ["tech", "pm", "safety", "ops", "data"],
    verified: false,
    verifiedBy: "",
  },
  {
    id: "datacenters",
    name: "Data centers",
    industry: "Technology & Digital Infrastructure",
    momentum: "accelerating",
    why: "Demand for AI and cloud computing is driving new data center construction across Texas, which needs reliable power, land, and skilled builders and operators.",
    work: "Building and commissioning facilities, keeping critical systems running around the clock, and managing vendors, equipment, and power.",
    skills: ["ops", "tech", "pm", "safety", "logistics"],
    verified: false,
    verifiedBy: "",
  },
  {
    id: "storage",
    name: "Grid-scale energy storage",
    industry: "Energy & Climate",
    momentum: "accelerating",
    why: "Texas has become one of the largest markets for battery storage as the grid adds more solar and wind power.",
    work: "Developing and financing battery sites, managing construction, operating systems, and analyzing when to store and sell power.",
    skills: ["tech", "pm", "finance", "data", "ops"],
    verified: false,
    verifiedBy: "",
  },
  {
    id: "otsecurity",
    name: "Industrial cybersecurity",
    industry: "Technology & Digital Infrastructure",
    momentum: "rising",
    why: "As plants, pipelines, and the grid go digital, Houston's energy companies need people who can protect the systems that control physical operations.",
    work: "Assessing risks, setting security policies, training teams, and responding to incidents in operational settings.",
    skills: ["tech", "safety", "ops", "data", "training"],
    verified: false,
    verifiedBy: "",
  },
  {
    id: "space",
    name: "Aerospace",
    industry: "Aerospace",
    momentum: "emerging",
    why: "Houston's NASA heritage and the Houston Spaceport at Ellington are drawing companies that build space stations, lunar landers, and spacesuits.",
    work: "Managing complex programs, coordinating suppliers, ensuring quality and safety, and building partnerships with customers.",
    skills: ["tech", "pm", "logistics", "safety", "sales"],
    verified: false,
    verifiedBy: "",
  },
  {
    id: "resilience",
    name: "Resilient infrastructure",
    industry: "Construction",
    momentum: "rising",
    why: "After major storms, Houston is investing in flood control, stronger buildings, and grid hardening, creating steady work for builders, planners, and project leaders.",
    work: "Leading construction projects, managing budgets and schedules, coordinating crews, and working with public agencies and communities.",
    skills: ["pm", "safety", "finance", "logistics", "client"],
    verified: false,
    verifiedBy: "",
  },
  {
    id: "healthtech",
    name: "Health tech & life sciences",
    industry: "Health & life sciences",
    momentum: "emerging",
    why: "The Texas Medical Center, the largest medical complex in the world, is expanding into research, biotech, and health technology through projects like TMC Helix Park.",
    work: "Running research operations, managing data and compliance, supporting product launches, and training clinical and business teams.",
    skills: ["data", "ops", "safety", "pm", "training", "client"],
    verified: false,
    verifiedBy: "",
  },
] as const;